Plotting Lesson Callouts
UMSWC/curriculum pull request #103
Opened 2021-02-04 15:22 UTC by MrFlick

These changes mostly add callouts to clarify some key points

Tidyverse (#63)
Quotes vs No Quotes (#97)
Different table types (#92)

2021-02-04 16:09 UTC, jmoltzau commented on _episodes_rmd/01-r-plotting.Rmd
> +> There are many different ways to store data in R. Most objects have a table-like structure with rows and columns. We will refer to these objects generally as "data objects". If you've used R before
...`read_csv` work with objects called "tibbles", which ...

2021-02-04 16:22 UTC, jmoltzau commented on _episodes_rmd/01-r-plotting.Rmd
> +Let's take a look at the full dataset. We could use `View()`, the way we did for the smaller dataset, but if your data is too big, it might take too long to load. Luckily, R offers way to look at par
... Luckily, R offers a way to look ...

2021-02-04 16:23 UTC, jmoltzau commented on _episodes_rmd/01-r-plotting.Rmd
> +Let's review the columns and the types of data stored in out dataset to decide how we should group things together. To get an overview of our data object, we can look at the structure of `gapminder_d
did you mean 'our dataset'?

2021-02-04 16:26 UTC, jmoltzau commented on _episodes_rmd/01-r-plotting.Rmd
> +If you have a lot of different columns to try to plot or have distinguishable subgroups in your data, a powerful plotting technique called faceting might come in handy. When you facet your plot, you
.... you basically make a bunch of much smaller plots ...

2021-02-04 16:28 UTC, jmoltzau commented on _episodes_rmd/01-r-plotting.Rmd
> +Note that `facet_wrap` requires this extra helper function called `vars()` in order to pass in the column names. It's a lot like the `aes()` function, but it doesn't require an aesthetic name. We can
... We can see in this output that we get a ...

2021-02-04 16:32 UTC, jmoltzau commented on _episodes_rmd/01-r-plotting.Rmd
> +Notice that this map helps to show that we actually have some gaps in the data. We are missing observations for counties like Russia and many countries in central Africa. Thus it's important to ackno
... Thus, it's important ...

2021-02-04 16:34 UTC, jmoltzau requested changes
Looks great! Very minor edits.

2021-02-04 16:42 UTC, kelly-sovacool commented
Hi @MrFlick @jmoltzau, if there are any issues that this PR fully resolves, can you use the resolves keyword in front of each issue in the description (first comment) so they'll be closed automatically? See example here: #94

2021-02-04 16:47 UTC, kelly-sovacool commented
Perfect, thank you @MrFlick!

2021-02-04 17:04 UTC, MrFlick commented
@kelly-sovacool This branch will need to be re-built before merging to build the md from the rmd.

2021-02-04 19:28 UTC, zenalapp approved these changes

2021-02-04 20:19 UTC, merged

2021-02-05 06:01 UTC, MrFlick commented
I noticed these changes were merged but the rendered HTML on the website page has not changed. It think the main branch still needs to run the make/compile step to update the lesson.

2021-02-05 16:30 UTC, zenalapp commented
Yep - @kelly-sovacool is going to run that once all the pull requests have been merged.