Iss 89 move man intro
UMSWC/curriculum pull request #125
Opened 2021-02-04 16:53 UTC by tomkoset

Resolves #89

2021-02-04 17:00 UTC, barnierc reviewed
There's an R-data-analysis file also included in this push. I'm not sure if this is supposed to be here/merged. @kelly-sovacool Maybe you could work with @tomkoset to figure out what happened with the merge conflicts, here?

2021-02-04 19:18 UTC, kelly-sovacool requested changes
Rather than deleting the file, we'll actually need to checkout out the version of the file from before the commit in this branch which introduced changes.

2021-02-04 21:09 UTC, tomkoset commented
Okay, I think I resolved the issue with the r-data-analysis file

2021-02-05 16:07 UTC, kelly-sovacool approved these changes

2021-02-05 16:07 UTC, merged